1oT-organization/hotelity-frontend

hotelity/src/component/customer/CustomerInit.vue, hotelity/src/component/customer/CustomerList.vue
- Customer List 기본 틀 제작
어떤 변경 사항이 있나요?
=> [Feat] Customer 기본

hotelity/src/component/customer/CustomerInit.vue, hotelity/src/component/customer/CustomerList.vue
고객 리스트 화면 출력 및 페이징 처리 기능 구현 완료
Resolves: #4
어떤 변경 사항이 있나요?
=> [Feat] 고객/전체고객 - 고객 리스트 출력

hotelity/src/component/customer/CustomerList.vue
고객 리스트 엑셀 다운 기능 구현 완료
Resolves: #7
어떤 변경 사항이 있나요?
=> [Feat]: 고객/고객리스트-엑셀 다운로드

hotelity/src/component/customer/CustomerList.vue
고객 전체 리스트 정렬 기능 구현. 맴버십 등급, 국가 백엔드 정렬 수정 필요.
Resolves: #8 
어떤 변경 사항이 있나요?
=> [Feat] 고객/고객리스트 정렬 기능 구현

hotelity/src/component/employee/EmployeeList.vue
직원 전체 조회 페이지 모든 기능 구현 완료
Resolves: #20, #19, #18, #16
어떤 변경 사항이 있나요?
=> [Feat] 직원/직원조회 직원 전체 조회

hotelity/src/component/employee/EmployeeList.vue, hotelity/src/component/sales/Coupon.vue, hotelity/src/component/sales/Membership.vue, hotelity/src/router/index.js
쿠폰 종류 전체 조회 기능 구현 완료
Resolves: #77, #79, #80, #85
어떤 변경 사항이 있나요?
=> [Feat] 마케팅/쿠폰 -  쿠폰 종류 전체 조회

hotelity/src/component/hotel-service/reservation/ReservationCheckinBtn.vue, hotelity/src/component/hotel-service/reservation/ReservationList.vue, hotelity/src/component/hotel-service/reservation/ReservationSideBar.vue, hotelity/src/router/index.js
- 체크박스 체크 후 체크인 버튼을 누르면 axios를 통해 stay_tb에 투숙이 등록됨
- 조회된 리스트에서 stayStatus가 1인 경우 체크 박스가 checked 상태로 비활성화
- 체크인 이벤트 발생 시 '체크인 되었습니다' 팝업이 뜬 후 페이지 새로고침됨
Resolves: #30 
어떤 변경 사항이 있나요?
=> [Feat] 호텔 서비스/예약- 체크인 기능 구현 완료

hotelity/src/component/employee/EmployeeInfo.vue, hotelity/src/router/index.js
- EmployeeInfo Page 개발 중. 스타일 수정 필요
- Axios를 통해 직원 정보 조회 완료
#117 
어떤 변경 사항이 있나요?
=> [Feat] EmployeeInfo Page 완료

hotelity/src/component/employee/EmployeeInfo.vue, hotelity/src/component/employee/EmployeeStay.vue, hotelity/src/router/index.js
- 직원별 투숙 정보 페이지 구현 완료
- Router를 통해 EmployeeInfo 페이지와 합해야함
어떤 변경 사항이 있나요?
=> [Feat] 직원별 투숙 정보 페이지 완료

hotelity/src/component/customer/CustomerList.vue, hotelity/src/component/hotel-service/payment/PaymentList.vue, hotelity/src/component/sales/Coupon.vue, hotelity/src/component/sales/Voc.vue, hotelity/src/router/index.js
VOC 전체 조회 기능 구현 완료
Resolves: #63, #64, #65
어떤 변경 사항이 있나요?
=> [Feat] 마케팅/VOC - 전체 조회 기능

hotelity/src/component/sales/CouponIssue.vue, hotelity/src/router/index.js
발급 쿠폰 전체 조회 기능 구현 완료.
Resolves: #86 
어떤 변경 사항이 있나요?
=> [Feat] 쿠폰/발급 쿠폰 전체 조회 기능

hotelity/src/component/hotel-management/RoomList.vue, hotelity/src/router/index.js
객실 리스트 전체 조회 기능 구현 완료
Resolves: #48, #49, #50, #51
어떤 변경 사항이 있나요?
=> [Feat] 객실/객실 리스트 전체 조회

hotelity/src/component/hotel-management/BranchList.vue, hotelity/src/component/sales/Notice.vue, hotelity/src/component/sales/NoticeInfo.vue, hotelity/src/router/index.js
지점 리스트 쪽 등록 수정 삭제 예시 추가
Resolves: #44 
Resolves: #45
Resolves: #46 
Resolves: #47 
어떤 변경 사항이 있나요?
=> [Feat] 지점 리스트에 수정, 삭제 모달 및 팝업, 등록 추가

hotelity/src/component/hotel-service/reservation/ReservationCalendar.vue, hotelity/src/component/hotel-service/reservation/ReservationList.vue, hotelity/src/component/hotel-service/reservation/ReservationNavbar.vue
- FullCalendar의 날짜 선택 시 해당 일자에 체크인 예약된 리스트를 화면에 출력
Resolves: #132 
어떤 변경 사항이 있나요?
=> [Feat] 호텔 서비스/예약 - 캘린더 날짜 선택 시 체크인 일자 별 예약 리스트 출력

hotelity/src/api/apiClient.js, hotelity/src/api/apiService.js, hotelity/src/component/common/navbar/Navbar.vue, hotelity/src/component/common/sidebar/Sidebar.vue, hotelity/src/component/customer/Customer.vue, hotelity/src/component/customer/CustomerInit.vue, hotelity/src/component/customer/CustomerList.vue, hotelity/src/component/employee/EmployeeList.vue, hotelity/src/component/hotel-management/Ancillary.vue, hotelity/src/component/hotel-management/BranchList.vue, hotelity/src/component/hotel-management/RoomList.vue, hotelity/src/component/hotel-service/payment/PaymentList.vue, hotelity/src/component/hotel-service/stay/StayList.vue, hotelity/src/component/marketing/Campaign.vue, hotelity/src/component/sales/Coupon.vue, hotelity/src/component/sales/Membership.vue, hotelity/src/component/sales/Notice.vue, hotelity/src/component/sales/Voc.vue, hotelity/src/router/router.js
=> [Feat] 화면 라우팅 설정

hotelity/src/App.vue, hotelity/src/component/login/Login.vue, hotelity/src/component/sales/CouponToCustomer.vue, hotelity/src/component/sales/NoticeInfo.vue, hotelity/src/router/router.js
- RoomDetails Header 제거
어떤 변경 사항이 있나요?
=> [Refactor] RoomDetails 헤더 제거

hotelity/src/component/TestMainContent.vue, hotelity/src/component/home/BarChart.vue, hotelity/src/component/home/Home.vue, hotelity/src/component/home/MainContent.vue, hotelity/src/component/home/PieChart.vue
- Main 화면 구성, Chart 아래 부분 구현
어떤 변경 사항이 있나요?
=> [Feat] Main 화면 구성

hotelity/src/component/hotel-service/payment/PaymentList.vue, hotelity/src/component/sales/Coupon.vue, hotelity/src/component/sales/Membership.vue, hotelity/src/component/sales/Voc.vue, hotelity/src/router/router.js
- 결제 리스트에 결제 금액에 대한 정보가 없어 추가
- 고객명과 결제 타입명의 데이터가 표시되지 않아 수정
- 쿠폰 리스트와 멤버십 리스트에서 행을 클릭 할 때 고객 리스트 화면으로 연결되지 않도록 navigate 주석 처리
Resolves: #150 
어떤 변경 사항이 있나요?
=> [refactor] 호텔 서비스/결제 - 결제 리스트에 결제 금액 컬럼 추가 및 데이터 누락 수정

hotelity/src/api/apiService.js, hotelity/src/component/home/MainContent.vue
=> Refactor: "추가된 GPT 관련 API 메소드 추출 및 API 파일에서 관리"

hotelity/src/api/apiClient.js, hotelity/src/component/home/MainContent.vue, hotelity/src/component/hotel-service/reservation/ReservationCalendar.vue, hotelity/src/component/hotel-service/stay/StayCheckoutBtn.vue, hotelity/src/component/hotel-service/stay/StayList.vue
- 다른 컴포넌트의 폰트와 통일 시킴
어떤 변경 사항이 있나요?
=> [Refactor] 메인 화면 AI 폰트 수정

hotelity/src/component/home/MainContent.vue
- 다른 컴포넌트의 폰트와 통일 시킴
어떤 변경 사항이 있나요?
=> [Refactor] AI 대시보드 폰트 수정

hotelity/src/api/apiClient.js, hotelity/src/component/hotel-service/payment/PaymentList.vue, hotelity/src/component/hotel-service/stay/StayList.vue
- 이름 검색 시 동명이인을 구별하기 위해 고객 코드 추가
어떤 변경 사항이 있나요?
=> [refactor] 호텔 서비스/결제 - 결제 내역 조회 시 고객 코드 추가

hotelity/src/component/hotel-management/RoomDetails.vue, hotelity/src/component/hotel-service/reservation/ReservationCheckinBtn.vue, hotelity/src/component/hotel-service/stay/StayCheckoutBtn.vue
- RoomDetails.vue, StayCheckoutBtn.vue, ReservationCheckinBtn.vue의 메소드 호출 주소를 axios(localhost)를 사용한 직접 호출 에서 api를 사용한 간접 호출로 변경
어떤 변경 사항이 있나요?
=> [Refactor] localhost 주소 -> api로 변경

hotelity/src/api/apiClient.js, hotelity/src/component/hotel-service/reservation/ReservationInfo.vue, hotelity/src/component/hotel-service/reservation/ReservationList.vue
- 특정 예약 선택 시 모달창 띄우기 진행 중
- apiClients의 api 요청 주소 localhost로 변경
어떤 변경 사항이 있나요?
=> [Feat] 호텔 서비스 / 코드 중간 통합

hotelity/src/component/employee/EmployeeList.vue, hotelity/src/component/hotel-management/Ancillary.vue, hotelity/src/component/hotel-management/BranchList.vue, hotelity/src/component/hotel-management/FacilityList.vue, hotelity/src/component/hotel-management/RoomList.vue, hotelity/src/component/marketing/Campaign.vue, hotelity/src/component/marketing/TemplateList.vue, hotelity/src/component/sales/Coupon.vue, hotelity/src/component/sales/CouponIssue.vue, hotelity/src/component/sales/Membership.vue, hotelity/src/component/sales/Notice.vue, hotelity/src/component/sales/Voc.vue
=> [Refactor] 전체 조회 스타일 추가

hotelity/src/component/customer/CustomerList.vue, hotelity/src/component/employee/EmployeeList.vue, hotelity/src/component/hotel-management/Ancillary.vue, hotelity/src/component/hotel-management/BranchList.vue, hotelity/src/component/hotel-management/RoomList.vue, hotelity/src/component/sales/Coupon.vue, hotelity/src/component/sales/Notice.vue, hotelity/src/component/sales/Voc.vue
- 컬럼 간 길이 조절
- 리스트 중 불필요 컬럼 제거 및 컬럼 순서 조정
어떤 변경 사항이 있나요?
=> [Refactor] 리스트 불필요 컬럼 제거 및 길이 조절

hotelity/src/component/hotel-service/reservation/ReservationList.vue, hotelity/src/component/hotel-service/stay/StayList.vue
- 투숙 리스트 선택 시 특정 투숙 내역 조회 모달창 기능 추가
- 모달창에서 체크아웃 하는 방식으로 변경
Resolves: #172 
어떤 변경 사항이 있나요?
=> [Feat] 호텔서비스/투숙-특정 투숙 내역 조회 및 체크아웃 방식 변경

hotelity/src/component/hotel-service/reservation/ReservationCalendar.vue, hotelity/src/component/hotel-service/reservation/ReservationList.vue
- 예약 캘린더를 넘길 때 캘린더 이벤트의 예약 건 수가 누적되어 증가하는 현상을 수정하였음
Resolves: #174 
어떤 변경 사항이 있나요?
=> [Bug] 호텔서비스/예약-캘린더 이벤트 누적 증가 에러 수정

hotelity/src/component/customer/CustomerList.vue, hotelity/src/component/employee/EmployeeList.vue, hotelity/src/component/hotel-management/Ancillary.vue, hotelity/src/component/hotel-management/FacilityList.vue, hotelity/src/component/hotel-management/RoomList.vue, hotelity/src/component/hotel-service/payment/PaymentList.vue, hotelity/src/component/hotel-service/reservation/ReservationList.vue, hotelity/src/component/hotel-service/stay/StayList.vue, hotelity/src/component/marketing/Campaign.vue, hotelity/src/component/marketing/TemplateList.vue, hotelity/src/component/sales/Coupon.vue, hotelity/src/component/sales/Membership.vue, hotelity/src/component/sales/Notice.vue, hotelity/src/component/sales/NoticeInfo.vue, hotelity/src/component/sales/Voc.vue
- 모든 리스트의 필터 컨테이너 넓이 및 위치 조정
Resolves: #176 
어떤 변경 사항이 있나요?
=> [Feat] 공통 / 필터 컨테이너 넓이 및 위치 조정

hotelity/src/App.vue, hotelity/src/component/login/Login.vue
로그인 시 사이드 바 버그 수정
어떤 변경 사항이 있나요?
=> [Fix] 로그인 시 버그 수정

hotelity/src/component/customer/CustomerList.vue, hotelity/src/component/hotel-management/AncillaryDetails.vue, hotelity/src/component/hotel-management/RoomDetails.vue, hotelity/src/component/marketing/Campaign.vue, hotelity/src/component/sales/VocSelect.vue
- 반응형 템플릿 테스트
- 룸 디테일, 부대시설 디테일 수정
어떤 변경 사항이 있나요?
=> [Refactor] 반응형 템플릿 테스트

hotelity/src/component/hotel-management/AncillaryDetails.vue
사진 클릭 시 확대 및 다시 돌아가게 기능 구현
어떤 변경 사항이 있나요?
=> [Refactor] 사진 확대

hotelity/src/api/apiService.js, hotelity/src/component/hotel-service/stay/StayList.vue
- 모달창에서 투숙 수정 기능 구현
- 모달창에서 투숙 삭제 기능 구현
Resolves: #37 , #38 
어떤 변경 사항이 있나요?
=> [Feat] 호텔 서비스/투숙 수정 및 삭제 기능 구현 완료

hotelity/src/component/hotel-management/AncillaryDetails.vue, hotelity/src/component/hotel-management/RoomDetails.vue
=> [Refactor] 사진 확대 기능 수정

hotelity/src/api/apiService.js, hotelity/src/component/common/Footer.vue, hotelity/src/component/hotel-service/reservation/ReservationList.vue
- 메인 화면 하단의 Guide Download 버튼을 누르면 사용자 가이드 pdf가 다운되도록 설정
어떤 변경 사항이 있나요?
=> [Feat] 공통 / 사용자 가이드 pdf  다운로드 연동

hotelity/src/api/apiService.js, hotelity/src/component/sales/Voc.vue, hotelity/src/component/sales/VocSelect.vue
=> [Feat] Voc 답변 기능 포함 VocSelect 구현 완료

hotelity/src/component/common/Footer.vue, hotelity/src/component/hotel-service/reservation/ReservationList.vue, hotelity/src/component/sales/NoticeInfo.vue, hotelity/src/component/sales/VocSelect.vue
- 공지 조회 페이지를 VOC 페이지와 동일하게 스타일 수정
Resolves: #193 
어떤 변경 사항이 있나요?
=> [Refactor] 영업관리/공지 조회 페이지 스타일 수정

hotelity/src/component/employee/EmployeeInfo.vue
- 특정 직원 정보 조회 화면에서 삭제 버튼 눌러 삭제
- 모달 창 띄워 직원 정보 수정
Resolves: #22 , #23  
어떤 변경 사항이 있나요?
=> [Feat] 직원 정보 수정, 삭제 기능

hotelity/src/component/common/Footer.vue, hotelity/src/component/common/navbar/Navbar.vue, hotelity/src/component/hotel-management/AncillaryDetails.vue, hotelity/src/component/marketing/Campaign.vue, hotelity/src/component/sales/Notice.vue, hotelity/src/component/sales/NoticeInit.vue, hotelity/src/router/router.js
- 공지사항 등록 기능 및 화면 추가
어떤 변경 사항이 있나요?
=> [Feat] 공지사항 등록 추가 완료

hotelity/src/component/sales/Notice.vue, hotelity/src/component/sales/NoticeInfo.vue, hotelity/src/component/sales/NoticeInit.vue
- 새로운 공지 등록 시 페이지 새로고침 하도록 추가
어떤 변경 사항이 있나요?
=> [Refactor] 영업 관리 / 공지 등록 시 페이지 새로고침

hotelity/src/component/home/MainContent.vue, hotelity/src/component/sales/NoticeInfo.vue
=> [Feat] 메인 로딩 수정

hotelity/src/component/employee/EmployeeInfo.vue
- 프로필 수정 버튼 스타일 수정
- 프로필 삭제 버튼 스타일 수정
- 프로필 이미지 업로드 버튼 스타일 및 가시성 개선
- 수정, 삭제, 이미지 버튼 위치 변경
어떤 변경 사항이 있나요?
=> [Refactor] 직원 프로필 수정/삭제/이미지업로드 버튼 수정

hotelity/src/component/home/PieChart.vue, hotelity/src/component/marketing/CampaignSend.vue, hotelity/src/component/sales/Voc.vue
- 캠페인 발송화면 날짜 설정
- VOC 컬럼 순서 수정
어떤 변경 사항이 있나요?
=> [Refactor] 캠페인 발송화면/VOC리스트 수정

hotelity/src/component/hotel-service/reservation/ReservationList.vue, hotelity/src/component/marketing/Campaign.vue
- 발송 날짜가 Invalid Date로 뜨던 문제 해결
- 멤버십 등급이 뜨지않던 문제 해결
어떤 변경 사항이 있나요?
=> [Bug] 마케팅/멤버십 등급, 발송 날짜 연동 오류 수정

hotelity/src/component/hotel-service/reservation/ReservationList.vue
- 예약 리스트 컬럼 길이 수정
어떤 변경 사항이 있나요?
=> [Refactor] 예약 컬럼 길이 수정

hotelity/src/component/employee/EmployeeList.vue, hotelity/src/component/hotel-service/payment/PaymentList.vue, hotelity/src/component/hotel-service/stay/StayList.vue, hotelity/src/component/marketing/Campaign.vue, hotelity/src/component/marketing/TemplateInfo.vue, hotelity/src/component/marketing/TemplateList.vue, hotelity/src/component/sales/CouponIssue.vue, hotelity/src/component/sales/Membership.vue, hotelity/src/component/sales/VocSelect.vue
- 투숙 리스트 화면 필터 아이콘 제거
- axios 요청 코드 apiService 사용하여 요청하도록 변경
- 직원 리스트 검색 카테고리에서 전화번호 제거
- 직원 리스트 정렬 시 이름, 내선번호, 이메일만 컬러 들어감 수정
어떤 변경 사항이 있나요?
=> [Fix] 버그 수정
